### ISSUE TITLE
Add multiple written languages, or add languages from other countries

### ISSUE THREAD

**Issue by jdnjk** [neoforged/Documentation#131]
添加多种文字语言，或者添加其他国家的语言
Add multiple written languages, or add languages from other countries

**Comment by IchHabeHunger54** [comment]
Quoting @ChampionAsh5357 from #67:
> After discussing translations with some of the other members, we ended up determining we do not have the capacity and the infrastructure to accept translations to other languages. It would be difficult to validate the quality of the PR and keep it maintained without a dedicated team or review process. We have discussed other solutions such as third party links or Crowdin translations, but those have the same issues with validation and infrastructure that we are not yet set up to handle.

> We will be revisiting translations in the future once we have more team members that can take off some load from our existing team and some more stable infrastructure, however. So, until then, we will keep this PR open. We would also like to ask if you could mark this as a draft since the documentation will likely be updated many times before we can get around to revisiting this topic.

> Thank you for the contribution, and apologies for the inconvenience.

So TL;DR: Currently impossible due to limited manpower and infrastructure, but may be possible at some point in the future.
