### ISSUE TITLE
Recipe use example missing how to get the RecipeManager

### ISSUE THREAD

**Issue by jcotton42** [neoforged/Documentation#154]
In the code sample under https://docs.neoforged.net/docs/resources/server/recipes/#the-crafting-mechanic, the variable `recipes` is used without showing how to get it.

I asked on the Discord, got this response

> oop, seems like a minor omission -- after the `level.isClientSide` check, you should be able to cast the level to a `ServerLevel` (directly or via instanceof pattern matching, whichever you feel better about) and then call `getRecipeManager`

**Comment by HenryLoenwind** [comment]
Note that getRecipeManager() is on Level, not ServerLevel. However, the client-server handling in this example is not the best. Cancelling the event only on the server and letting it run on the client can cause all kinds of desyncs, depending on what happens next.
