### ISSUE TITLE
Remove mention of DistExecutor

### ISSUE THREAD

**Issue by tmvkrpxl0** [neoforged/Documentation#16]
In FancyModLoader DistExecutor is marked deprecated and will be removed. so we should now stop directing users to it.
https://github.com/neoforged/Documentation/blob/main/docs/concepts/sides.md?plain=1#L31-L66
This section should be rewritten to demonstrate other ways of checking physical sides without class loading issue.

**Comment by Shadows-of-Fire** [comment]
Yeah, we need to resurrect https://github.com/MinecraftForge/MergeTool/pull/8 in some form

**Comment by Shadows-of-Fire** [comment]
https://github.com/neoforged/MergeTool/pull/1
