### ISSUE TITLE
BlockEntityWithoutLevelRenderer Issue

### ISSUE THREAD

**Issue by CoolerProYT** [neoforged/Documentation#168]
I am trying to render fluid for my Fluid Tank when it is inside inventory, but when i want to override the initializeClient method, this error happen:
![image](https://github.com/user-attachments/assets/335675c6-ac72-4083-8c19-001fbce607a4)

How do i create renderer for an block entity item?

**Comment by Technici4n** [comment]
There is an event that you can use to register the client item extensions.
