### ISSUE TITLE
BEWLR Page is out of date

### ISSUE THREAD

**Issue by ZestyBlaze** [neoforged/Documentation#172]
https://docs.neoforged.net/docs/items/bewlr/

Now that we are moving away from using the `initializeClient` event and moving towards using the `RegisterClientExtensionsEvent` event, the page is not only a little lackluster in it's explanations and could probably use a bit more documentation, but as well we probably want to show devs how to use the event for this, not the method that's being removed in 1.21.2

**Comment by IchHabeHunger54** [comment]
You probably had an old version of the page open, because we merged a PR fixing this just yesterday. The BEWLR article has been merged into the BER article, and has been updated to reflect the new method of registering.

Thank you for opening this issue regardless!
