### ISSUE TITLE
Loot Table Datagen example calls non-existent super in 1.21.1

### ISSUE THREAD

**Issue by sylv256** [neoforged/Documentation#179]
https://docs.neoforged.net/docs/resources/server/loottables/#datagen
The example provided calls a nonexistent super constructor.
Specifically this looks wrong:
```java
public class MyLootTableSubProvider implements LootTableSubProvider {
    // The parameter is provided by the lambda (see below). It can be stored and used to lookup other registry entries.
    public MyLootTableSubProvider(HolderLookup.Provider lookupProvider) {
        super(lookupProvider);
    }
```
It should probably be a `record` for simplicity.

**Comment by ChampionAsh5357** [comment]
Records and classes are functionally the same in this case. It does not matter which is used, as the provider is not meant to model data, only to generate loot tables.

As such, a class serves the purpose just fine.

**Comment by sylv256** [comment]
> Records and classes are functionally the same in this case. It does not matter which is used, as the provider is not meant to model data, only to generate loot tables.
> 
> As such, a class serves the purpose just fine.

I don't think you see the problem here. It's calling `super` in something that doesn't have a super constructor.

**Comment by ChampionAsh5357** [comment]
> I don't think you see the problem here. It's calling `super` in something that doesn't have a super constructor.

I did not, I missed that as I only looked at the error reported. I still don't think it's necessary to make the example a record, but yes, the `super` call should be removed.
