### ISSUE TITLE
BlockEntityWithoutLevelRenderer rendering block entity in inventory as item

### ISSUE THREAD

**Issue by CoolerProYT** [neoforged/Documentation#180]
I am trying to use BlockEntityWithoutLevelRenderer to render my Fluid Tank Block entity when it is inside inventory, but failed, i use

```java
event.registerItem(
    new ModClientItemExtensions(),
    ModBlocks.FLUID_TANK.get().asItem()
);
```

Nothing is rendering other can default model for it.

**Comment by ChampionAsh5357** [comment]
Does your item model have a parent of `minecraft:builtin/entity`? This is required, or the `BakedModel` instance for the item must have `#isCustomRenderer` return true. The code is technically correct, but as there is still an issue, I will keep this open.

**Comment by CoolerProYT** [comment]
I have updated my item model to 
```json
{
  "parent": "minecraft:builtin/entity"
}
```
But now I am encountering another issue, only the fluid ir endering with BEWLR is rendering and the fluid tank is not rendering.

**Comment by ChampionAsh5357** [comment]
Yes, using a BEWLR on its own will not render an existing block model as well. I'm not sure what you are referring to when you say the fluid tank texture here, however. I would recommend joining the discord and asking for help there as this seems to be more of modder support than a specific issue with the docs, other than the part I've outlined.

**Comment by CoolerProYT** [comment]
Alright, Thanks.
