### ISSUE TITLE
Why is applyTint in DynamicFluidContainerModel not used anymore

### ISSUE THREAD

**Issue by Ata-Luko** [neoforged/Documentation#183]
i'm trying to make buckets for my custom fluids and i don't understand how to apply the tint of the fluid to the bucket

**Comment by ChampionAsh5357** [comment]
You need to register a [`ItemColor`](https://docs.neoforged.net/docs/1.20.6/resources/client/models/#tinting) for your item. This will be dressed in the 1.21.2/3 update
