### ISSUE TITLE
Clarify which version apply to the live documentation

### ISSUE THREAD

**Issue by LelouBil** [neoforged/Documentation#207]
Hello, I am writing this issue because I got very confused about this section of the documentation

https://docs.neoforged.net/docs/blockentities/#creating-and-registering-block-entities

In the header, the version is listed as 1.21.x, so I thought that using the 1.21 MDK (linked in the documentation) would allow me to use the registration example, however after having errors and looking around in the neoforged repos, I found out that the constructor used in the documentation was actually added to neoforged 1.21.2, and the 1.21 MDK is using 1.21.1.

I am not sure if this is an issue with the documentation versioning (1.21.x using 1.21.2 only features) or the 1.21 MDK not using the latest 1.21 version ? (But on https://projects.neoforged.net/neoforged/neoforge 1.21.2 is listed as Beta, so I am not sure).

Or maybe the 1.21.x version of the documentation should specify 1.21.2+ and/or specify that it applies to a neoforged version currently in Beta.

**Comment by ChampionAsh5357** [comment]
The versioning works similar to the NeoForge repo, except we don't make new docs for versions that didn't have that many major changes.

The `.x` branches always refer to the latest neoforge version (beta counts as well, as we are only using it as a marker that breaking changes are still allowed in the internals). Any other version works as a maximum bound. You can see the available versions in the dropdown in the top right corner. Currently, there is 1.20.4, 1.20.6, 1.21.1, and 1.21.x. This means that the doc range covers [1.20.3, 1.20.4], [1.20.5, 1.20.6], [1.21, 1.21.1], and [1.21.2, 1.21.3], respectively. 1.21.4, as there are a lot of changes, will be migrated to 1.21.x, where 1.21.3 will have its own subsection.

**Comment by LelouBil** [comment]
Thanks for the clarification about the documentation versioning. I think always listing the specific version(s) instead of ".x" would be easier for users of the documentation.

Something should also be done for the MDK linked in the "Getting Started" section, currently the documentation links an MDK that doesn't match the version of the code examples inside that same documentation version.

**Comment by LelouBil** [comment]
Thank you very much! However the linked MDK for 1.21.2-1.21.3 is still the 1.21 MDK, that uses NeoForge for 1.21.1

**Comment by LelouBil** [comment]
Maybe this should be a separate issue
