### ISSUE TITLE
Chunk Pre-generation

### ISSUE THREAD

**Issue by Shindur** [neoforged/Documentation#215]
Before the split off from Forge, there was a command to pre-gen chunks. It was /forge generate and you could specify the location, radius, and dimension the chunks were pre-generated in. I know there's mods out there to do this, but having this brought back as baked into NeoForge itself would be a big help. I looked to see if maybe it got renamed to a different command, but none that I can see in as of version 21.1.90.

Thank you for looking into this!

**Comment by Erdragh** [comment]
It exists and it is called `/neoforge generate` and is present in 21.1.90. It has also received improvements to make it work more reliably

**Comment by Erdragh** [comment]
Here's the PR addressing some issues with it: https://github.com/neoforged/NeoForge/pull/937

Also, this is the docs repo and probably the wrong place to ask for this kind of thing.
