### ISSUE TITLE
Saved Data is outdated

### ISSUE THREAD

**Issue by tmvkrpxl0** [neoforged/Documentation#27]
https://github.com/neoforged/Documentation/blame/main/docs/datastorage/saveddata.md#L21
> `DimensionDataStorage#computeIfAbsent` takes in three arguments: a function to load NBT data into a SD and return it, a supplier to construct a new instance of the SD, and the name of the `.dat` file stored within the `data` folder for the implemented level.

On 1.20.2, it takes in 2 arguments instead. The first argument is a record instead of function. The record in which takes in default constructor for the Saved Data, NBT deserializer, and nullable DFU Type.

**Comment by Matyrobbrt** [comment]
Closed by #47
