### ISSUE TITLE
"Getting Started with Neo' section out of date

### ISSUE THREAD

**Issue by Arkan501** [neoforged/Documentation#31]
Step 4 under "From Zero to Modding" contains outdated information for run configs. `genIntellijRuns` and `genEclipseRuns` no longer exist. This issue was already reported on the MDK repository in [this pull request](https://github.com/neoforged/MDK/pull/17) a few weeks ago.

**Comment by Arkan501** [comment]
Actually, several things appear to be outdated in this section.

**Comment by ChampionAsh5357** [comment]
I would imagine the entirety of the documentation is outdated as NeoForge keeps rewriting more and more things. Someone will come around and address the changes, or I will once my new laptop arrives in some amount of time.

For now, this will be closed by #28 at some point.

**Comment by XFactHD** [comment]
Fixed by #28
